---
name: Checks

on: [push]  # push events only 


jobs: # job definition
  test-lint: # job name
    name: Test and Lint # job name
    runs-on: ubuntu-20.04 # run on ubuntu 20.04
    steps: # steps definition
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USER }} # Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub password
      - name: Checkout
        uses: actions/checkout@v2 # checkout code
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test" # run tests
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8" # run flake8


